POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlVLS08iLCJpZCI6IjYwMzhjOGM2Yjg4NzcwNTlmYzRjNTUxYSIsImlhdCI6MTYxNDM0MDM5Nn0.GFOBjvZ3wHqUB7KYGCu4s5aBjGxMobR3BRnpuCcBMOM

{
"title": "sportss",
"author": "seppoo",
"url": "www.sportt.com",
"likes": 0
}